import io
import logging

try:
    from weasyprint import HTML, CSS
    WEASYPRINT_INSTALLED = True
except (ImportError, OSError):
    WEASYPRINT_INSTALLED = False

try:
    from xhtml2pdf import pisa
    import PyPDF2
    XHTML2PDF_INSTALLED = True
except (ImportError, OSError):
    XHTML2PDF_INSTALLED = False

logger = logging.getLogger('ats_resume_scorer')

def generate_combined_pdf(html_docs: dict[str, str]) -> bytes:
    if WEASYPRINT_INSTALLED:
        try:
            documents = []
            # Render all HTML strings to WeasyPrint Document objects
            for name, html_str in html_docs.items():
                doc = HTML(string=html_str).render()
                documents.append(doc)
            
            # Merge them into the first document
            first_doc = documents[0]
            for other_doc in documents[1:]:
                for page in other_doc.pages:
                    first_doc.pages.append(page)
                    
            # Write combined PDF bytes
            return first_doc.write_pdf()
        except Exception as e:
            logger.warning(f"WeasyPrint failed to render PDF: {e}. Trying fallback xhtml2pdf.")

    if XHTML2PDF_INSTALLED:
        try:
            pdf_parts = []
            for name, html_str in html_docs.items():
                pdf_buffer = io.BytesIO()
                pisa_status = pisa.CreatePDF(html_str, dest=pdf_buffer)
                if pisa_status.err:
                    logger.error(f"xhtml2pdf rendering error for {name}: {pisa_status.err}")
                pdf_parts.append(pdf_buffer.getvalue())

            if not pdf_parts:
                raise RuntimeError("No PDF parts were generated by xhtml2pdf.")

            # Merge the PDF parts using PyPDF2
            merger = PyPDF2.PdfMerger()
            for pdf_bytes in pdf_parts:
                merger.append(io.BytesIO(pdf_bytes))
            
            out_buffer = io.BytesIO()
            merger.write(out_buffer)
            merger.close()
            return out_buffer.getvalue()
        except Exception as e:
            logger.error(f"Fallback xhtml2pdf rendering failed: {e}")
            raise RuntimeError(f"PDF generation failed using both WeasyPrint and xhtml2pdf: {e}")

    raise ImportError(
        "PDF generation is unavailable. WeasyPrint failed to load its binary system libraries (GObject/Pango), "
        "and xhtml2pdf is not installed or available."
    )
